### ISSUE TITLE
Is there a reason for the `!` at the end of the css files>

### ISSUE THREAD

**Issue by laurianek** [guygriffiths/deframetrics#2]
in files `js/pie-chart.js` and `js/strip-main.js`

there is a line to import the css and I wonder why there is a bang at the end of the file? It makes it difficult to import it via webpack because of this bang.
```import '../css/pie-chart.css!'```

I also wonder if there is no way of making a compiled library that would be easy to import regardless of the packaging tool used

**Comment by guygriffiths** [comment]
Lauriane,Yep, there's no standard import syntax for CSS - the exclamation mark is how the systemjs CSS plugin detects css.Cheers,GuyOn 22 May 2017 08:58, Lauriane Kayungu-N <notifications@github.com> wrote:—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by laurianek** [comment]
Thanks no problem
